from flask import Flask, request
import gspread
from google.oauth2.service_account import Credentials
scopes = ['https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive']

credentials = Credentials.from_service_account_file(
    'FILE_ADDRESS', scopes=scopes)


@app.route('/api/pump_logs', methods=['POST'])
def handle_json():
    if request.is_json:
        data = request.json
        # use the same key in arduino code. Any password or any key generated by you
        if data.get('api_key') == "YOUR_API_KEY":
            print(data.get('epoch'))
            print(data.get('start'))
            print(data.get('end'))
            print(data.get('percBegin'))
            print(data.get('percEnd'))
            print(data.get('timetaken'))
            print(data.get('errMsg'))

            gc = gspread.authorize(credentials)
            # open a google sheet
            gs = gc.open_by_key(
                "your_sheet_key").worksheet('Sheet1')
            gs.append_row([data.get('epoch'), data.get('start'), data.get('end'), data.get(
                'percBegin'), data.get('percEnd'), data.get('timetaken'), data.get('errMsg')], table_range='A2')
            return "201 Created"
        else:
            return "401 Unauthorized"
    else:
        return "501 Not Implemented"
